### ISSUE TITLE
Application to compression? 

### ISSUE THREAD

**Issue by wbrickner** [Ranlot/single-parameter-fit#16]
Hello,

I'm wondering what the precision requirements are on the values of `a`? Are there known bounds?

If they're low, I'd like to use this technique for approximating media, like image tiles or audio clips.

**Comment by Ranlot** [comment]
Look at the end of section 1.2 in the paper and you will see a discussion of precision requirements with an example.  Essentially, the number of digits in the parameter will be:
`(number of bits you wish to use to encode each sample) x (total number of samples)`
