### ISSUE TITLE
Missing data file

### ISSUE THREAD

**Issue by jamesmyatt** [Ranlot/single-parameter-fit#2]
Thanks for this paper; it's very interesting. However, the pickle file "resources/cifar10/cifar-10-batches-py/data_batch_1" is missing, but is used by "cifar10.ipynb".

**Comment by Ranlot** [comment]
This file is a little bigger so I preferred not to have it on GitHub.  You can download the raw data directly from the [CIFAR-10](https://www.cs.toronto.edu/~kriz/cifar.html) webpage.  *(After extracting the relevant file, you can upload it to Binder or your local fork.)*
